# Generated by Django 4.2 on 2023-05-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imag',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
